### ISSUE TITLE
How to increase thickness of seek bar?

### ISSUE THREAD

**Issue by MountainX** [squentin/gmusicbrowser#231]
I use the standard playlist layout. I would like to double or triple the thickness (vertical height) of the seek bar (i.e., the widget that shows and controls the position of the now playing song) so that I can more easily use my mouse to change the position.

My current customizations consist only of a trivial change to the fonts:

$ cat ~/.themes/gmbtheme/gtk-3.0/gtk.css
```
@import url("/usr/share/themes/Adwaita-dark/gtk-3.0/gtk.css");
 * {
  color: #ffffff;
  font: 20px "DejaVu Sans";
}
```
I don't want to make any complex theme or layout changes that would be difficult to maintain, so I'm hoping there is an equally simple way to increase the thickness of the seek bar. Any suggestions? Thank you.

In case it is helpful, here is a snippet of my gmbrc file

```
Layout: Playlist
LayoutB: Browser
LayoutF: default fullscreen
LayoutS: Quick Search with SongTree
LayoutT: full with buttons
Layouts:
  Browser:
    FilterPane0:
      hidebb: 0
      hidetabs: ''
      min: 1
      page: ~
      page_added:
        type: added.month
      page_folder:
        simplify: smart
      page_lastplay:
        type: lastplay.month
      pages: savedtree|artists|album|genre|label|folder|added|lastplay|rating
```
